/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *nom_liste;
  GtkWidget *id_teteliste;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *t1;
  GSList *t1_group = NULL;
  GtkWidget *t2;
  GtkWidget *t3;
  GtkWidget *label2;
  GtkWidget *aff;
  GtkWidget *ajout;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label3;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  nom_liste = gtk_entry_new ();
  gtk_widget_show (nom_liste);
  gtk_fixed_put (GTK_FIXED (fixed1), nom_liste, 128, 72);
  gtk_widget_set_size_request (nom_liste, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (nom_liste), _("nom_liste"));
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_liste), 8226);

  id_teteliste = gtk_entry_new ();
  gtk_widget_show (id_teteliste);
  gtk_fixed_put (GTK_FIXED (fixed1), id_teteliste, 128, 128);
  gtk_widget_set_size_request (id_teteliste, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (id_teteliste), _("id_teteliste"));
  gtk_entry_set_invisible_char (GTK_ENTRY (id_teteliste), 8226);

  jour_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed1), jour, 112, 232);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed1), mois, 184, 232);
  gtk_widget_set_size_request (mois, 60, 27);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (mois), GTK_UPDATE_IF_VALID);

  annee_adj = gtk_adjustment_new (2022, 0, 10000, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed1), annee, 256, 232);
  gtk_widget_set_size_request (annee, 60, 27);

  t1 = gtk_radio_button_new_with_mnemonic (NULL, _("9"));
  gtk_widget_show (t1);
  gtk_fixed_put (GTK_FIXED (fixed1), t1, 64, 176);
  gtk_widget_set_size_request (t1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (t1), t1_group);
  t1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (t1));

  t2 = gtk_radio_button_new_with_mnemonic (NULL, _("10"));
  gtk_widget_show (t2);
  gtk_fixed_put (GTK_FIXED (fixed1), t2, 192, 176);
  gtk_widget_set_size_request (t2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (t2), t1_group);
  t1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (t2));

  t3 = gtk_radio_button_new_with_mnemonic (NULL, _("11"));
  gtk_widget_show (t3);
  gtk_fixed_put (GTK_FIXED (fixed1), t3, 320, 176);
  gtk_widget_set_size_request (t3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (t3), t1_group);
  t1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (t3));

  label2 = gtk_label_new (_("Ajouter une liste"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 96, 32);
  gtk_widget_set_size_request (label2, 216, 16);

  aff = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (aff);
  gtk_fixed_put (GTK_FIXED (fixed1), aff, 240, 304);
  gtk_widget_set_size_request (aff, 66, 29);

  ajout = gtk_button_new ();
  gtk_widget_show (ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout, 96, 304);
  gtk_widget_set_size_request (ajout, 96, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajout), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) t1, "toggled",
                    G_CALLBACK (on_t1_toggled),
                    NULL);
  g_signal_connect ((gpointer) t2, "toggled",
                    G_CALLBACK (on_t2_toggled),
                    NULL);
  g_signal_connect ((gpointer) t3, "toggled",
                    G_CALLBACK (on_t3_toggled),
                    NULL);
  g_signal_connect ((gpointer) aff, "clicked",
                    G_CALLBACK (on_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout, "clicked",
                    G_CALLBACK (on_ajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, nom_liste, "nom_liste");
  GLADE_HOOKUP_OBJECT (window1, id_teteliste, "id_teteliste");
  GLADE_HOOKUP_OBJECT (window1, jour, "jour");
  GLADE_HOOKUP_OBJECT (window1, mois, "mois");
  GLADE_HOOKUP_OBJECT (window1, annee, "annee");
  GLADE_HOOKUP_OBJECT (window1, t1, "t1");
  GLADE_HOOKUP_OBJECT (window1, t2, "t2");
  GLADE_HOOKUP_OBJECT (window1, t3, "t3");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, aff, "aff");
  GLADE_HOOKUP_OBJECT (window1, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *treels;
  GtkWidget *rech;
  GtkWidget *re;
  GtkWidget *listadd;
  GtkWidget *vote1;
  GtkWidget *main_liste;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  treels = gtk_tree_view_new ();
  gtk_widget_show (treels);
  gtk_fixed_put (GTK_FIXED (fixed2), treels, 56, 64);
  gtk_widget_set_size_request (treels, 300, 200);

  rech = gtk_entry_new ();
  gtk_widget_show (rech);
  gtk_fixed_put (GTK_FIXED (fixed2), rech, 40, 24);
  gtk_widget_set_size_request (rech, 168, 27);
  gtk_tooltips_set_tip (tooltips, rech, _("saisir l'identifiant ou le nom"), NULL);
  gtk_entry_set_text (GTK_ENTRY (rech), _("Saisir la liste a chercher"));
  gtk_entry_set_invisible_char (GTK_ENTRY (rech), 8226);

  re = gtk_button_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (re);
  gtk_fixed_put (GTK_FIXED (fixed2), re, 240, 24);
  gtk_widget_set_size_request (re, 96, 29);

  listadd = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (listadd);
  gtk_fixed_put (GTK_FIXED (fixed2), listadd, 400, 112);
  gtk_widget_set_size_request (listadd, 96, 32);

  vote1 = gtk_button_new_with_mnemonic (_("Voter"));
  gtk_widget_show (vote1);
  gtk_fixed_put (GTK_FIXED (fixed2), vote1, 400, 168);
  gtk_widget_set_size_request (vote1, 96, 32);

  main_liste = gtk_button_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (main_liste);
  gtk_fixed_put (GTK_FIXED (fixed2), main_liste, 400, 232);
  gtk_widget_set_size_request (main_liste, 96, 32);

  g_signal_connect ((gpointer) treels, "row_activated",
                    G_CALLBACK (on_treels_row_activated),
                    NULL);
  g_signal_connect ((gpointer) re, "clicked",
                    G_CALLBACK (on_re_clicked),
                    NULL);
  g_signal_connect ((gpointer) listadd, "clicked",
                    G_CALLBACK (on_listadd_clicked),
                    NULL);
  g_signal_connect ((gpointer) vote1, "clicked",
                    G_CALLBACK (on_vote1_clicked),
                    NULL);
  g_signal_connect ((gpointer) main_liste, "clicked",
                    G_CALLBACK (on_main_liste_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, treels, "treels");
  GLADE_HOOKUP_OBJECT (window2, rech, "rech");
  GLADE_HOOKUP_OBJECT (window2, re, "re");
  GLADE_HOOKUP_OBJECT (window2, listadd, "listadd");
  GLADE_HOOKUP_OBJECT (window2, vote1, "vote1");
  GLADE_HOOKUP_OBJECT (window2, main_liste, "main_liste");
  GLADE_HOOKUP_OBJECT_NO_REF (window2, tooltips, "tooltips");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *treecond;
  GtkWidget *noi;
  GtkWidget *id_t;
  GtkWidget *date;
  GtkWidget *modif_liste;
  GtkWidget *button3;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  treecond = gtk_tree_view_new ();
  gtk_widget_show (treecond);
  gtk_fixed_put (GTK_FIXED (fixed3), treecond, 24, 104);
  gtk_widget_set_size_request (treecond, 328, 192);

  noi = gtk_label_new (_("label1"));
  gtk_widget_show (noi);
  gtk_fixed_put (GTK_FIXED (fixed3), noi, 56, 24);
  gtk_widget_set_size_request (noi, 240, 16);

  id_t = gtk_label_new (_("label2"));
  gtk_widget_show (id_t);
  gtk_fixed_put (GTK_FIXED (fixed3), id_t, 56, 48);
  gtk_widget_set_size_request (id_t, 240, 16);

  date = gtk_label_new (_("label3"));
  gtk_widget_show (date);
  gtk_fixed_put (GTK_FIXED (fixed3), date, 56, 72);
  gtk_widget_set_size_request (date, 240, 16);

  modif_liste = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (modif_liste);
  gtk_fixed_put (GTK_FIXED (fixed3), modif_liste, 384, 136);
  gtk_widget_set_size_request (modif_liste, 86, 29);

  button3 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 384, 192);
  gtk_widget_set_size_request (button3, 86, 29);

  g_signal_connect ((gpointer) treecond, "row_activated",
                    G_CALLBACK (on_treecond_row_activated),
                    NULL);
  g_signal_connect ((gpointer) modif_liste, "clicked",
                    G_CALLBACK (on_modif_liste_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, treecond, "treecond");
  GLADE_HOOKUP_OBJECT (window3, noi, "noi");
  GLADE_HOOKUP_OBJECT (window3, id_t, "id_t");
  GLADE_HOOKUP_OBJECT (window3, date, "date");
  GLADE_HOOKUP_OBJECT (window3, modif_liste, "modif_liste");
  GLADE_HOOKUP_OBJECT (window3, button3, "button3");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed4;
  GtkWidget *nom_cond;
  GtkWidget *prenom_cond;
  GtkWidget *CIN_cond;
  GtkWidget *ajout_cond;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label4;
  GtkWidget *lid_liste;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4), fixed4);

  nom_cond = gtk_entry_new ();
  gtk_widget_show (nom_cond);
  gtk_fixed_put (GTK_FIXED (fixed4), nom_cond, 40, 88);
  gtk_widget_set_size_request (nom_cond, 80, 19);
  gtk_entry_set_text (GTK_ENTRY (nom_cond), _("Nom "));
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_cond), 8226);

  prenom_cond = gtk_entry_new ();
  gtk_widget_show (prenom_cond);
  gtk_fixed_put (GTK_FIXED (fixed4), prenom_cond, 136, 88);
  gtk_widget_set_size_request (prenom_cond, 80, 19);
  gtk_entry_set_text (GTK_ENTRY (prenom_cond), _("Prenom"));
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom_cond), 8226);

  CIN_cond = gtk_entry_new ();
  gtk_widget_show (CIN_cond);
  gtk_fixed_put (GTK_FIXED (fixed4), CIN_cond, 232, 88);
  gtk_widget_set_size_request (CIN_cond, 104, 19);
  gtk_entry_set_text (GTK_ENTRY (CIN_cond), _("CIN"));
  gtk_entry_set_invisible_char (GTK_ENTRY (CIN_cond), 8226);

  ajout_cond = gtk_button_new ();
  gtk_widget_show (ajout_cond);
  gtk_fixed_put (GTK_FIXED (fixed4), ajout_cond, 144, 160);
  gtk_widget_set_size_request (ajout_cond, 112, 32);
  gtk_tooltips_set_tip (tooltips, ajout_cond, _("Ajouter un condidat"), NULL);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ajout_cond), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, FALSE, 0);

  lid_liste = gtk_label_new (_("Identifiant de la liste "));
  gtk_widget_show (lid_liste);
  gtk_fixed_put (GTK_FIXED (fixed4), lid_liste, 8, 40);
  gtk_widget_set_size_request (lid_liste, 361, 24);

  g_signal_connect ((gpointer) ajout_cond, "clicked",
                    G_CALLBACK (on_ajout_cond_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4, nom_cond, "nom_cond");
  GLADE_HOOKUP_OBJECT (window4, prenom_cond, "prenom_cond");
  GLADE_HOOKUP_OBJECT (window4, CIN_cond, "CIN_cond");
  GLADE_HOOKUP_OBJECT (window4, ajout_cond, "ajout_cond");
  GLADE_HOOKUP_OBJECT (window4, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window4, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window4, image2, "image2");
  GLADE_HOOKUP_OBJECT (window4, label4, "label4");
  GLADE_HOOKUP_OBJECT (window4, lid_liste, "lid_liste");
  GLADE_HOOKUP_OBJECT_NO_REF (window4, tooltips, "tooltips");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed5;
  GtkWidget *vote2;
  GtkWidget *comboboxentry1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);

  vote2 = gtk_button_new_with_mnemonic (_("Voter"));
  gtk_widget_show (vote2);
  gtk_fixed_put (GTK_FIXED (fixed5), vote2, 136, 136);
  gtk_widget_set_size_request (vote2, 120, 24);
  gtk_tooltips_set_tip (tooltips, vote2, _("Voter"), NULL);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxentry1, 104, 64);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);

  g_signal_connect ((gpointer) vote2, "clicked",
                    G_CALLBACK (on_vote2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, vote2, "vote2");
  GLADE_HOOKUP_OBJECT (window5, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT_NO_REF (window5, tooltips, "tooltips");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed6;
  GtkWidget *label5;
  GtkWidget *ordre_liste;
  GtkWidget *Return_liste;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window6), fixed6);

  label5 = gtk_label_new (_("Ordre des listes \303\251l\303\250ctorales"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed6), label5, 80, 24);
  gtk_widget_set_size_request (label5, 216, 25);

  ordre_liste = gtk_tree_view_new ();
  gtk_widget_show (ordre_liste);
  gtk_fixed_put (GTK_FIXED (fixed6), ordre_liste, 48, 72);
  gtk_widget_set_size_request (ordre_liste, 300, 200);

  Return_liste = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (Return_liste);
  gtk_fixed_put (GTK_FIXED (fixed6), Return_liste, 72, 312);
  gtk_widget_set_size_request (Return_liste, 66, 29);

  g_signal_connect ((gpointer) Return_liste, "clicked",
                    G_CALLBACK (on_Return_liste_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window6, label5, "label5");
  GLADE_HOOKUP_OBJECT (window6, ordre_liste, "ordre_liste");
  GLADE_HOOKUP_OBJECT (window6, Return_liste, "Return_liste");

  return window6;
}

GtkWidget*
create_Main (void)
{
  GtkWidget *Main;
  GtkWidget *fixed7;
  GtkWidget *listes;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label6;

  Main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Main), _("Accueil"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Main), fixed7);

  listes = gtk_button_new ();
  gtk_widget_show (listes);
  gtk_fixed_put (GTK_FIXED (fixed7), listes, 48, 56);
  gtk_widget_set_size_request (listes, 88, 64);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (listes), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Les\nlistes"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) listes, "clicked",
                    G_CALLBACK (on_listes_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Main, Main, "Main");
  GLADE_HOOKUP_OBJECT (Main, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Main, listes, "listes");
  GLADE_HOOKUP_OBJECT (Main, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Main, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Main, image3, "image3");
  GLADE_HOOKUP_OBJECT (Main, label6, "label6");

  return Main;
}

